# Avi_kaushik

1. Write a program to check whether an year entered by an user is leap year or not

In [43]:
def checkYear(year):
    if (year % 4) == 0:
        if (year % 100) == 0:
            if (year % 400) == 0:
                return True
            else:
                return False
        else:
             return True
    else:
        return False 
year = int(input("enter year: "))
if(checkYear(year)):
    print("Leap Year")
else:
    print("Not a Leap Year")

enter year: 2004
Leap Year


2. Take a string containing punctuation marks as an input from user and write a program to remove all the punctuation marks from a string

In [2]:
def punc(string):
    punctuations='''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for x in string:
        if x in punctuations:
            string=string.replace(x, "")
    print(string)
string=input("Enter: ")
punc(string)

Enter: My*&*( na)*^^*me
My name


3. Take two separate numbers as input from the user and Write a program to swap 2 numbers without using temporary variable

In [3]:
x=int(input())
y=int(input())
x=x+y
y=x-y
x=x-y
print("x=",x,"y=",y)

20
30
x= 30 y= 20


4. Write a program to print product of following variables

In [4]:
x=10
y="15"
prod=x*int(y)
print(prod)

150


5. Write a program to print following pattern

In [6]:
def pattern(n):
    num = 97
    for i in range(0,n):
        for j in range(0,i+1):
            ch=chr(num)
            print(ch, end=" ")
            num=num+1
        print("\r")
n=6
pattern(n)

a 
b c 
d e f 
g h i j 
k l m n o 
p q r s t u 


6. Write a program to print tables from 2 to n, where n is provided by user

In [10]:
def tables(n):
    for i in range(2,n+1):
        for j in range(1,11):
            print(i,"*",j,"=",i*j)
        print("\r")
n=int(input("Enter: "))
tables(n)

Enter: 4
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40



7. Write a program to read height (in centimeters) from user and then convert it to feet and inches

In [12]:
def convert(height):
    feet=height/30.48
    inch=height*0.3937008
    print(feet,"ft")
    print(inch,"in")
height=int(input("height in centimeters: "))
convert(height)

height in centimeters: 20
0.6561679790026247 ft
7.874016 in


8. Write a program to print following pattern

                                            *
                                            * * 
                                            * * *
                                            * *
                                            *

In [18]:
def pattern1(n):
    for i in range(0,n):
        for j in range(0,i-1):
            print("*", end=" ")
        print("\r")
    for i in range(n,0,-1):
        for j in range(0,i-1):
            print("*", end=" ")
        print("\r")
n=4
pattern1(n)



* 
* * 
* * * 
* * 
* 



9. Below list contains age and name of five students. Convert the list into a dictionary such that the name is taken as key and the age before their name is taken as thier respective value in the dictionary

students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton'] Output: {'Jon':26, 'Roger':34, 'Jessica':13, 'Monica':24, 'Ashton':65}

In [44]:
students = [26,'Jon',34,'Roger',13,'Jessica',24,'Monica',65,'Ashton']
new_dict = {students[i+1]: students[i] for i in range(0, len(students), 2)}
new_dict

{'Jon': 26, 'Roger': 34, 'Jessica': 13, 'Monica': 24, 'Ashton': 65}

10. Write a program to check whether two strings, taken from user, are anagram or not

In [19]:
def anagram(str1,str2):
    if(sorted(str1)==sorted(str2)):
        print("anagrams")
    else:
        print("not anagrams")
str1=str(input("enter string 1: "))
str2=str(input("enter string 2: "))
anagram(str1,str2)

enter string 1: qwerty
enter string 2: ytrewq
anagrams


12. Write a program that prints a list of sour fruits from the below tuple:


fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour') )


Output: Sour Fruits: ['Lemon', 'Grapes', 'Kiwi', 'Orange', 'Limes']


In [45]:
fruits = (('Lemon','sour'), ('DragonFruit', 'Sweet'), ('Grapes','soUr'), ('Kiwi','Sour'), ('Apples','sweet'), ('Orange','sour'), ('Blueberries','sweet'), ('Limes','Sour') )
s_f = []
for i in range(len(fruits)):
    if fruits[i][1].lower() == 'sour':
        s_f.append(fruits[i][0])
print(f"Sour Fruits: {s_f}")

Sour Fruits: ['Lemon', 'Grapes', 'Kiwi', 'Orange', 'Limes']


13. Given below are the list of positive and negative words. Also a list of tweets is provided. Separate out the positive and negative comments


positive = ['good','awesome', 'best', 'nice']


negative = ['worst','awful', 'bad']


tweets = ['This government policies are good', 'bad implementation', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'The wine tastes awful', 'It's nice to hear this little kid's laugh']

In [46]:
positive = ['good','awesome', 'best', 'nice']
negative = ['worst','awful', 'bad']

tweets = ['This government policies are good', 
'bad implementation', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', 'The wine tastes awful', "It's nice to hear this little kid's laugh"]

p_tweet = []
n_tweet = []

for tweet in tweets:
    for i in range(len(positive)):
        if positive[i] in tweet:
            p_tweet.append(tweet)
for tweet in tweets:
    if tweet not in p_tweet:
        n_tweet.append(tweet)
print(f"Positive Comments : {p_tweet}\n")
print(f"Negative Comments : {n_tweet}")

Positive Comments : ['This government policies are good', 'The way he played showed that he is one of the best players in the world', 'Her acting in the play was awesome', "It's nice to hear this little kid's laugh"]

Negative Comments : ['bad implementation', 'The wine tastes awful']


14. Write a program that performs multiplication of the following two matrix

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[1,8,1],
    [3,7,3],
    [4,5,9]]

In [47]:
X = [[1,2,3], [4 ,5,6],[7 ,8,9]]

Y = [[1,8,1], [3,7,3], [4,5,9]]

x1 = np.array(X)
y1 = np.array(Y)

print('Multiplication: ', x1*y1)
print('Dot Multiplication: ', x1@y1)

Multiplication:  [[ 1 16  3]
 [12 35 18]
 [28 40 81]]
Dot Multiplication:  [[ 19  37  34]
 [ 43  97  73]
 [ 67 157 112]]


15. Write a program to remove space from keys of the given dictionary

Employee = {'emp 01' : 'Raj', 'emp 02' : 'Sheela', 'emp 0 3 ': 'Joseph'};

Output:
New dictionary : {'emp01': 'Raj', 'emp02': 'Sheela', 'emp03': 'Joseph'}

In [48]:
Employee = {'emp 01' : 'Raj', 'emp 02' : 'Sheela', 'emp 0 3 ': 'Joseph'}
new_emp = {}
for k,v in Employee.items():
    k = k.replace(' ', '')
    new_emp[k] = v
print(new_emp)

{'emp01': 'Raj', 'emp02': 'Sheela', 'emp03': 'Joseph'}


16. Write a program to display the subjects for which the scores are between 300 and 500 (inclusive) in the given dataframe

Use the dataframe given below:
Subject 	Score
Maths 	345
Physics 	432
Chemistry 	456
Biology 	234
Geology 	254

In [49]:
import pandas as pd
data = [['Maths', 345], ['Physics', 432], ['Chemistry', 456], ['Biology', 234], ['Geology', 254]]
df = pd.DataFrame(data, columns=['Subject', 'Score' ])
df[(df['Score'] > 300) & (df['Score'] <= 500)]

Subject  Score
0      Maths    345
1    Physics    432
2  Chemistry    456

17. Write a program to find numbers between 10000 to 20000 from a given array¶

Use the list given below:

Sales = [1432,143223,2043332,1642357,54327,754338,12459,75435,224454,1433,12447,25532,86674,74338,12678]

In [29]:
Sales = [1432,143223,2043332,1642357,54327,754338,12459,75435,224454,1433,12447,25532,86674,74338,12678]
for i in Sales:
    if(i>10000 and i<20000):
        print(i,end=" ")

12459 12447 12678 

18. Write a program to sort the dataframe by Rank (in ascending order)

Use the dataframe given below:
Name 	Rank
Joy 	115
Mia 	451
Karan 	341
Tom 	84

In [50]:
data = [['Joy', 115], ['Mia', 451], ['Karan', 341], ['Tom', 84]]
df = pd.DataFrame(data, columns=['Name', 'Rank'])
df.sort_values('Rank')

Name  Rank
3    Tom    84
0    Joy   115
2  Karan   341
1    Mia   451

19. Use the data given in the question 18, to do the following:

Write a program to swap the 1st and 2nd row in a dataframe

In [51]:
data = [['Joy', 115], ['Mia', 451], ['Karan', 341], ['Tom', 84]]
df = pd.DataFrame(data, columns=['Name', 'Rank'])
df.iloc[0], df.iloc[1] = df.iloc[1], df.iloc[0]
df

Name  Rank
0    Mia   451
1    Joy   115
2  Karan   341
3    Tom    84

20. Write a program to replace 0 and 1 in Gender variable with M and F

Use the dataframe given below:
Id 	Name 	Age 	Gender
1 	Mia 	47 	1
2 	Sara 	38 	1
3 	Joy 	47 	0
4 	Karan 	41 	0

In [52]:
data = [[1,'Mia', 47, 1], [2,'Sara', 38, 1], [3,'Joy', 47, 0], [4,'Karan', 41, 0]]
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age', 'Gender'])
df.replace(to_replace = [1,0], value = ['F', 'M'])

ID   Name  Age Gender
0  F    Mia   47      F
1  2   Sara   38      F
2  3    Joy   47      M
3  4  Karan   41      M

21. Convert a 1D array to a 2D array containing 2 rows

Use the array given below:

dim_1 = ([331, 245, 246, 475, 348, 229])

In [59]:
import numpy as np
dim_1 = np.array([331, 245, 246, 475, 348, 229])
dim_1.reshape(2,3)

array([[331, 245, 246],
       [475, 348, 229]])

22. Find the average cost of each variety of product available in the three different shops

Use the data given below:

[[10, 20, 30], [17, 14, 21], [25, 15, 12]], columns=['product_a', 'product_b', 'product_c'], index=['Shop1', 'Shop2', 'Shop3']

In [54]:
shop_df = pd.DataFrame([[10, 20, 30], [17, 14, 21], [25, 15, 12]], columns=['product_a', 'product_b', 'product_c'],index=['Shop1', 'Shop2', 'Shop3'])
shop_df
print('Product A = ',shop_df['product_a'].mean())
print('Product B = ',shop_df['product_b'].mean())
print('Product C = ',shop_df['product_c'].mean())

Product A =  17.333333333333332
Product B =  16.333333333333332
Product C =  21.0


25. Create a series of 40 random numbers and transform it into a dataframe containing seven columns and five rows

In [56]:
number = pd.DataFrame(np.random.randint(0,100, (5,7)))
number

0   1   2   3   4   5   6
0  69  75  58   8  58  93  62
1  88  89   7   1  91  21  53
2  80  57   1  94  36  42  50
3  37  59  34  21  27  77  51
4  49  26  99  53  87  45  11

26. Get common elements from the two arrays

Use the array given below:

  test_a = np.array([11,12,13,22,23,44,43,24,45,36])
  test_b = np.array([17,22,13,22,47,34,39,44,29,28])

In [30]:
import numpy as np

test_a = np.array([11,12,13,22,23,44,43,24,45,36])
test_b = np.array([17,22,13,22,47,34,39,44,29,28])

print(np.intersect1d(test_a, test_b))

[13 22 44]


28. Compute total sales for each product and country

Use the dataframe given below:
Product 	Country 	Sales
A 	USA 	44000
J 	Japan 	43000
A 	Europe 	54000
L 	Japan 	95600
R 	Europe 	79000
A 	USA 	67000
R 	USA 	68000
J 	Japan 	38000
L 	USA 	59000
A 	Europe 	60000

In [63]:
sales = [['A', 'USA', 44000], ['J', 'Japan', 43000], ['A', 'Europe', 54000], ['L', 'Japan', 95600], ['R', 'Europe', 79000], ['A', 'USA', 67000], ['R', 'USA', 68000], ['J', 'Japan', 38000], ['L', 'USA', 59000], ['A', 'Europe', 60000]]

sales_df = pd.DataFrame(sales, columns=['Product', 'Country', 'Sales'])
sales_df.groupby(['Product', 'Country']).sum()

Sales
Product Country        
A       Europe   114000
        USA      111000
J       Japan     81000
L       Japan     95600
        USA       59000
R       Europe    79000
        USA       68000

30. Reverse each of the rows of the 2D array¶

Use the array given below:

num_array = np.arange(20).reshape(4,5)

In [64]:
num_array = np.arange(20).reshape(4,5)
for i in range(len(num_array)):
    num_array[i] = np.flip(num_array[i])
print(num_array)

[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
